### ISSUE TITLE
[Backlog] Add Front-page

### ISSUE THREAD

**Issue by killje** [killje/TripPlanner#14]
Story Points: 1

![front page design](https://www.notion.so/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2F45a412b5-f537-4681-98f1-22c63a537343%2FUntitled.png)

Acceptance Criteria:
- [x] The frontpage should be simple and clean, not cluttered.
- [x] The frontpage should have a way to go to the next page (map/activity page)

# User stories
- As a visitor of the website, I can go to the map, such that I can view the venues.
- As a visitor, I can read what the project is about on the frontpage, so that I know what I can use the service for.

**Comment by Producermark** [comment]
I believe @EmielRuchti will do this, so I changed the assigned member.

**Comment by killje** [comment]
I will do this. He needs to create a new issue for the image
