### ISSUE TITLE
CORE: Static Web Page Design

### ISSUE THREAD

**Issue by Producermark** [killje/TripPlanner#4]
For the first demo, we want to have the static webpages up and running.
Don’t bother about the dynamic content like showing actual activities for now.
Before adding the dynamic content, we need the following pages:

- [ ] Responsive menu bar
    - [ ] By default; minimized on small devices like phones.
- [ ] Landing page
    - [ ] Input field to enter a certain city
    - [ ] A way of selecting the amount of days
    - [ ] A way of submitting the form (button?)
- [ ] Selection of Activities-page
    - [ ] Showing a list of activities
    - [ ] For each individual activity:
        - [ ] Show the name of the activity
        - [ ] Show the description of the activity
        - [ ] Show a button as a means of selecting the activity
    - [ ] Show a button to continue to the next page
- [ ] Route Overview-page
    - [ ] A navigational menu-bar to select a particular day
    - [ ] Selecting each day will show a unique Map
    - [ ] Selecting each day will show an overview of the activites

Requirements: 

- Responsive design
- Each page should have a background and a (placeholder for a) logo
- Each page should be static first. We’re supposed to work incrementally, not like the waterfall method.

**Comment by killje** [comment]
This should probably be made a project instead of issues

**Comment by killje** [comment]
This is now a separate project
